# Form implementation generated from reading ui file 'menpai_config.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(268, 182)
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 111, 51))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(parent=dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 120, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "门派闯关配置"))
        self.label_2.setText(_translate("dialog", "<html><head/><body><p>在任务列表里的位置</p></body></html>"))
        self.label.setText(_translate("dialog", "任务位置"))
        self.pushButton_4.setText(_translate("dialog", "确定"))
